---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
    name: back-springboot
spec:
  lookupPolicy:
    local: false
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: back-springboot-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'back-springboot:develop'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java-test:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jarduini/jump-app-java-springboot.git'
      ref: master
  runPolicy: Serial
