---
apiVersion: v1
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: mongo
        version: v1
        template: mongo
      name: mongo
    stringData:
      database-admin-password: mongo
      database-password: mongo
      database-user: mongo
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Exposes the database server
      labels:
        app: mongo
        version: v1
        template: mongo
      name: mongo
    spec:
      ports:
        - name: tcp-27017
          port: 27017
          targetPort: 27017
      selector:
        app: mongo
        version: v1
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        description: Defines how to deploy the database
        template.alpha.openshift.io/wait-for-ready: 'true'
      labels:
        app: mongo
        version: v1
        template: mongo
      name: mongo
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: mongo
      template:
        metadata:
          labels:
            name: mongo
            app: mongo
            version: v1
          name: mongo
        spec:
          containers:
            - env:
                - name: MONGODB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: mongo
                - name: MONGODB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: mongo
                - name: MONGODB_DATABASE
                  value: sampledb
                - name: MONGODB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-admin-password
                      name: mongo
              image: image-registry.openshift-image-registry.svc:5000/openshift/mongodb:3.6
              livenessProbe:
                initialDelaySeconds: 30
                tcpSocket:
                  port: 27017
                timeoutSeconds: 1
              name: mongo
              ports:
                - containerPort: 27017
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                      --eval="quit()"
                failureThreshold: 3
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /var/lib/mongodb/data
                  name: mongo-data
          volumes:
            - emptyDir: {}
              name: mongo-data
kind: List
metadata: {}
